---
- name: Update cache
  ansible.builtin.apt:
    update_cache: true
    cache_valid_time: 3600

- name: Install required packages
  ansible.builtin.package:
    name:
      - 7zip
      - python3-dev
      - python3-pip
      - python3-distutils
      - unrar-free
      - unzip
    state: present

- name: Ensure Bazarr group exists
  ansible.builtin.group:
    name: "{{ arrs_bazarr_group }}"
    gid: "{{ arrs_bazarr_gid }}"
    state: present

- name: Ensure Bazarr user exists
  ansible.builtin.user:
    name: "{{ arrs_bazarr_user }}"
    group: "{{ arrs_bazarr_group }}"
    create_home: false
    shell: /usr/sbin/nologin
    uid: "{{ arrs_bazarr_uid }}"
    state: present

- name: Ensure Bazarr library directory exists
  ansible.builtin.file:
    path: /var/lib/bazarr
    state: directory
    owner: "{{ arrs_bazarr_user }}"
    group: "{{ arrs_bazarr_group }}"
    mode: "0755"

- name: Download Bazarr archive
  ansible.builtin.get_url:
    url: "{{ arrs_bazarr_url }}"
    dest: /root/bazarr.zip
    owner: root
    group: root
    mode: "0644"

- name: Ensure Bazarr installation directory exists
  ansible.builtin.file:
    path: /opt/Bazarr
    state: directory
    owner: "{{ arrs_bazarr_user }}"
    group: "{{ arrs_bazarr_group }}"
    mode: "0755"

- name: Extract Bazarr to /opt/Bazarr
  ansible.builtin.unarchive:
    src: /root/bazarr.zip
    dest: /opt/Bazarr
    owner: "{{ arrs_bazarr_user }}"
    group: "{{ arrs_bazarr_group }}"
    remote_src: true
  notify: Restart Bazarr

- name: Install Bazarr Python dependencies
  ansible.builtin.pip:
    requirements: /opt/Bazarr/requirements.txt
    extra_args: --break-package-system

- name: Deploy Bazarr systemd service
  ansible.builtin.template:
    src: bazarr.service.j2
    dest: /etc/systemd/system/bazarr.service
    mode: "0664"
    owner: root
    group: root
  notify: Restart Bazarr

- name: Ensure Bazarr service is enabled and started
  ansible.builtin.systemd:
    name: bazarr
    state: started
    enabled: true
