---
- name: Update APT cache
  ansible.builtin.apt:
    update_cache: true
    cache_valid_time: 3600

- name: Install required Chromium dependencies
  ansible.builtin.package:
    name:
      - chromium
      - chromium-common
      - chromium-driver
      - dumb-init
      - xvfb
    state: present

- name: Ensure Flaresolverr group exists
  ansible.builtin.group:
    name: "{{ arrs_flaresolverr_group }}"
    gid: "{{ arrs_flaresolverr_gid }}"
    state: present

- name: Ensure Flaresolverr user exists
  ansible.builtin.user:
    name: "{{ arrs_flaresolverr_user }}"
    group: "{{ arrs_flaresolverr_group }}"
    create_home: true
    shell: /usr/sbin/nologin
    uid: "{{ arrs_flaresolverr_uid }}"
    state: present

- name: Ensure Flaresolverr library directory exists
  ansible.builtin.file:
    path: /var/lib/flaresolverr
    state: directory
    owner: "{{ arrs_flaresolverr_user }}"
    group: "{{ arrs_flaresolverr_group }}"
    mode: "0755"

- name: Download Flaresolverr archive
  ansible.builtin.get_url:
    url: "{{ arrs_flaresolverr_url }}"
    dest: /root/flaresolverr_linux_x64.tar.gz
    owner: root
    group: root
    mode: "0644"

- name: Ensure Flaresolverr installation directory exists
  ansible.builtin.file:
    path: /opt/Flaresolverr
    state: directory
    owner: "{{ arrs_flaresolverr_user }}"
    group: "{{ arrs_flaresolverr_group }}"
    mode: "0755"

- name: Extract Flaresolverr to /opt/Flaresolverr
  ansible.builtin.unarchive:
    src: /root/flaresolverr_linux_x64.tar.gz
    dest: /opt
    owner: "{{ arrs_flaresolverr_user }}"
    group: "{{ arrs_flaresolverr_group }}"
    remote_src: true
  notify: Restart Flaresolverr

- name: Deploy Flaresolverr systemd service
  ansible.builtin.template:
    src: flaresolverr.service.j2
    dest: /etc/systemd/system/flaresolverr.service
    mode: "0664"
    owner: root
    group: root
  notify: Restart Flaresolverr

- name: Ensure Flaresolverr service is enabled and started
  ansible.builtin.systemd:
    name: flaresolverr
    state: started
    enabled: true
