---
# tasks file for ansible-arrs
- name: Install required packages
  ansible.builtin.package:
    name:
      - curl
      - sqlite3
    state: present

- name: Install ARR applications
  ansible.builtin.include_tasks: "{{ item }}"
  loop:
    - radarr.yml
    - prowlarr.yml
    - sonarr.yml
    - readarr.yml
    - bazarr.yml
    - flaresolverr.yml
