---
- name: Ensure Prowlarr group exists
  ansible.builtin.group:
    name: "{{ arrs_prowlarr_group }}"
    gid: "{{ arrs_prowlarr_gid }}"
    state: present

- name: Ensure Prowlarr user exists
  ansible.builtin.user:
    name: "{{ arrs_prowlarr_user }}"
    group: "{{ arrs_prowlarr_group }}"
    create_home: false
    shell: /usr/sbin/nologin
    uid: "{{ arrs_prowlarr_uid }}"
    state: present

- name: Ensure Prowlarr library directory exists
  ansible.builtin.file:
    path: /var/lib/prowlarr
    state: directory
    owner: "{{ arrs_prowlarr_user }}"
    group: "{{ arrs_prowlarr_group }}"
    mode: "0755"

- name: Download Prowlarr archive
  ansible.builtin.get_url:
    url: "{{ arrs_prowlarr_url }}"
    dest: /root/prowlarr.linux-core-x64.tar.gz
    owner: root
    group: root
    mode: "0644"

- name: Ensure Prowlarr installation directory exists
  ansible.builtin.file:
    path: /opt/Prowlarr
    state: directory
    owner: "{{ arrs_prowlarr_user }}"
    group: "{{ arrs_prowlarr_group }}"
    mode: "0755"

- name: Extract Prowlarr to /opt/Prowlarr
  ansible.builtin.unarchive:
    src: /root/prowlarr.linux-core-x64.tar.gz
    dest: /opt
    owner: "{{ arrs_prowlarr_user }}"
    group: "{{ arrs_prowlarr_group }}"
    remote_src: true
  notify: Restart Prowlarr

- name: Deploy Prowlarr systemd service
  ansible.builtin.template:
    src: prowlarr.service.j2
    dest: /etc/systemd/system/prowlarr.service
    mode: "0664"
    owner: root
    group: root
  notify: Restart Prowlarr

- name: Enable and start Prowlarr service
  ansible.builtin.systemd:
    name: prowlarr
    state: started
    enabled: true
