---
- name: Ensure Sonarr group exists
  ansible.builtin.group:
    name: "{{ arrs_sonarr_group }}"
    gid: "{{ arrs_sonarr_gid }}"
    state: present

- name: Ensure Sonarr user is present
  ansible.builtin.user:
    name: "{{ arrs_sonarr_user }}"
    group: "{{ arrs_sonarr_group }}"
    create_home: false
    system: true
    shell: /usr/sbin/nologin
    uid: "{{ arrs_sonarr_uid }}"
    state: present

- name: Ensure Sonarr lib directory exists
  ansible.builtin.file:
    path: /var/lib/sonarr
    state: directory
    owner: "{{ arrs_sonarr_user }}"
    group: "{{ arrs_sonarr_group }}"
    mode: "0755"

- name: Ensure Sonarr tar is present
  ansible.builtin.get_url:
    url: "{{ arrs_sonarr_url }}"
    dest: /root/sonarr.linux-core-x64.tar.gz
    owner: root
    group: root
    mode: "0644"

- name: Ensure Sonarr program file are in opt
  ansible.builtin.unarchive:
    src: /root/sonarr.linux-core-x64.tar.gz
    dest: /opt
    group: "{{ arrs_sonarr_user }}"
    owner: "{{ arrs_sonarr_group }}"
    remote_src: true
  notify: Restart Sonarr

- name: Ensure Sonarr service file is on remote
  ansible.builtin.template:
    src: sonarr.service.j2
    dest: /etc/systemd/system/sonarr.service
    mode: "0664"
    owner: root
    group: root

- name: Ensure Sonarr service is enabled and started
  ansible.builtin.service:
    name: sonarr
    state: started
    enabled: true
