---
- name: Ensure Sonarr group exists
  ansible.builtin.group:
    name: "{{ arrs_sonarr_group }}"
    gid: "{{ arrs_sonarr_gid }}"
    state: present

- name: Ensure Sonarr user exists
  ansible.builtin.user:
    name: "{{ arrs_sonarr_user }}"
    group: "{{ arrs_sonarr_group }}"
    create_home: false
    shell: /usr/sbin/nologin
    uid: "{{ arrs_sonarr_uid }}"
    state: present

- name: Ensure Sonarr library directory exists
  ansible.builtin.file:
    path: /var/lib/sonarr
    state: directory
    owner: "{{ arrs_sonarr_user }}"
    group: "{{ arrs_sonarr_group }}"
    mode: "0755"

- name: Download Sonarr archive
  ansible.builtin.get_url:
    url: "{{ arrs_sonarr_url }}"
    dest: /root/sonarr.linux-core-x64.tar.gz
    owner: root
    group: root
    mode: "0644"

- name: Ensure Sonarr installation directory exists
  ansible.builtin.file:
    path: /opt/Sonarr
    state: directory
    owner: "{{ arrs_sonarr_user }}"
    group: "{{ arrs_sonarr_group }}"
    mode: "0755"
  become: true

- name: Extract Sonarr to /opt/Sonarr
  ansible.builtin.unarchive:
    src: /root/sonarr.linux-core-x64.tar.gz
    dest: /opt
    owner: "{{ arrs_sonarr_user }}"
    group: "{{ arrs_sonarr_group }}"
    remote_src: true
  notify: Restart Sonarr

- name: Deploy Sonarr systemd service
  ansible.builtin.template:
    src: sonarr.service.j2
    dest: /etc/systemd/system/sonarr.service
    mode: "0664"
    owner: root
    group: root
  notify: Restart Sonarr

- name: Enable and start Sonarr service
  ansible.builtin.systemd:
    name: sonarr
    state: started
    enabled: true
