---
# handlers file for ansible-arrs
- name: Restart Prowlarr
  ansible.builtin.systemd:
    name: prowlarr
    state: restarted
    daemon_reload: true

- name: Restart Radarr
  ansible.builtin.systemd:
    name: radarr
    state: restarted
    daemon_reload: true

- name: Restart Sonarr
  ansible.builtin.systemd:
    name: sonarr
    state: restarted
    daemon_reload: true

- name: Restart Readarr
  ansible.builtin.systemd:
    name: readarr
    state: restarted
    daemon_reload: true

- name: Restart Bazarr
  ansible.builtin.systemd:
    name: bazarr
    state: restarted
    daemon_reload: true

- name: Restart FlareSolverr
  ansible.builtin.systemd:
    name: flaresolverr
    state: restarted
    daemon_reload: true
