---
# handlers file for ansible-arrs
- name: Restart Prowlarr
  ansible.builtin.service:
    name: prowlarr
    state: restarted

- name: Restart Radarr
  ansible.builtin.service:
    name: radarr
    state: restarted

- name: Restart Sonarr
  ansible.builtin.service:
    name: sonarr
    state: restarted
